### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by joy002** [ThestralMoon/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
   - Need to add the link to test file.
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
   - Need to add the link to test file.
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Please finished bug/input 3.

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by ThestralMoon** [comment]
**Bug/Input 1**

- Added link to test file

**Bug/Input 2**

-  Added link to test file

**Bug/Input 3**

-  Committed screenshot for bug/input 3
-  Added link to test file for bug/input 3
-  Symptom shown as command + output for bug/input 3
-  Description of relationship between bug, symptom, and input for bug/input 3

**Comment by joy002** [comment]
Please send the regrade request on gradescope if you need regrade.

**Comment by joy002** [comment]
Oh wait sorry I just saw it, however, for the link part we want you to use markdown for links. Ex. [link1](some link)

**Comment by joy002** [comment]
Please update those as soon as possible and send me another regrade request on gradescope. Thank you.

**Comment by ThestralMoon** [comment]
Formatted Links

**Comment by joy002** [comment]
Nice job. I have updated your grade.
